version: '3.9'

services:

    php:
        build: docker/php
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./migrations:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: picpay
            MYSQL_ROOT_PASSWORD: secret

    redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

volumes:
    mysql-data:
